#!/bin/env python

import os
import subprocess as sp

import pyke

pyke.init('0.1')

pyke.set_stages(
        ['bootstrap', 'configure', 'build', 'run'],
        config='configure',
        target_default='build')

CUR_DIR = os.path.dirname(os.path.abspath(__file__))

BUILD_DIR = os.path.join(CUR_DIR, 'build')

CXX_COMPILER = 'g++'

def build_cpp_file(rel_src, rel_bin):
    sp.check_call([CXX_COMPILER, os.path.join(CUR_DIR, rel_src), os.path.join(BUILD_DIR, rel_bin)], cwd=CUR_DIR, shell=False)


src = pyke.load('src')
