#!/bin/env python

import os
import subprocess as sp

import pyke

CUR_DIR = os.path.dirname(os.path.abspath(__file__))
BUILD_DIR = os.path.join(CUR_DIR, 'build')


pyke.init(
    version='0.1',
    stages=['bootstrap', 'config', 'build', 'run'],
    config_stage='config',
    default_stage='build',
    workspace=BUILD_DIR)


pyke.add_target(
    'list-targets',
    action=lambda: print('\n'.join(pyke.list_targets())))


pyke.add_target(
    'list-stages',
    action=lambda: print('\n'.join(pyke.list_stages())))


pyke.add_target(
    'list-all',
    dependencies=['list-targets', 'list-stages'])


def set_build_params():
    pyke.save_state('CXX_COMPILER', 'g++')


pyke.add_target(
    'config',
    stage='config',
    action=set_build_params)


pyke.load('pyke')
pyke.load('src')
