#!/bin/env python

import pyke

buildmod = pyke.pykefiles['root.pyke.build']
runmod = pyke.pykefiles['root.pyke.run']

pyke.add_target(
    'build-hello',
    action=buildmod.build_cpp_file,
    args=('src/hello/hello.cpp', 'bin/hello'))


pyke.add_target(
    'run-hello',
    action=runmod.run_bin,
    args=('bin/hello',))

